import type { DailyItem } from "@/src/types/daily-item";

const now = new Date().toISOString();

export const mockDailyItems: DailyItem[] = [
  {
    action: "把官方示例里的工具调用链路跑一遍，记录它能不能替代你现在手写脚本的一个步骤。",
    category: "ai_news",
    content_type: "news",
    created_at: now,
    published_at: now,
    reason: "这类更新会直接改变 AI Coding 工具能完成的任务边界，适合优先跟进。",
    score: 96,
    source: "Anthropic Docs",
    summary: "Claude Code 相关工作流继续向更长任务、更强上下文和更可控的自动化方向演进。",
    tags: ["Agent", "AI Coding", "CLI"],
    title: "Claude Code 工作流更新，Agent 编码任务更可控",
    url: "https://docs.anthropic.com/",
    what_happened: "Claude Code 相关工作流继续向更长任务、更强上下文和更可控的自动化方向演进。",
    why_it_matters: "它说明 AI Coding 正从补全工具变成可交付任务的执行环境，值得观察新的开发习惯。"
  },
  {
    action: "挑一个 MCP Server 接入本地项目资料，让 AI 能读 README、Issue 和最近提交。",
    category: "tool",
    content_type: "tool",
    created_at: now,
    published_at: now,
    reason: "MCP 正在变成 Agent 与真实工具、数据源之间的通用连接层。",
    score: 93,
    source: "GitHub",
    summary: "一批 MCP Server 和模板项目在 GitHub 上被持续收藏，覆盖浏览器、数据库、文件和 SaaS API。",
    tags: ["MCP", "Open Source", "Developer Tool"],
    title: "MCP Server 工具生态继续扩张",
    url: "https://github.com/topics/mcp",
    what_happened: "一批 MCP Server 和模板项目在 GitHub 上被持续收藏，覆盖浏览器、数据库、文件和 SaaS API。",
    why_it_matters: "这给个人项目提供了低成本扩展 Agent 能力的方式，不需要一开始就做复杂平台。"
  },
  {
    action: "看比赛主题和提交要求，选一个能做成作品集案例的 Agent 方向。",
    category: "hackathon",
    content_type: "opportunity",
    created_at: now,
    published_at: now,
    reason: "线上赛门槛低，题目适合做成可展示、可写进简历的个人项目。",
    score: 90,
    source: "Brabble Hackathons",
    summary: "新的 AI Agent 线上 Hackathon 开放报名，主题集中在自动化工作流和 AI 应用开发。",
    tags: ["Hackathon", "Agent", "Portfolio"],
    title: "AI Agent Hackathon 开放报名",
    url: "https://brabble.ai/",
    what_happened: "新的 AI Agent 线上 Hackathon 开放报名，主题集中在自动化工作流和 AI 应用开发。",
    why_it_matters: "它可以倒逼你在短时间内完成一个有演示、有文档、有复盘的 Agent 项目。"
  },
  {
    action: "阅读 SDK 示例，比较它和你当前 Next.js 项目里 pipeline/LLM 调用层的接口边界。",
    category: "tool",
    content_type: "tool",
    created_at: now,
    published_at: now,
    reason: "前端 AI 应用越来越依赖标准化 streaming、tool call 和 provider 抽象。",
    score: 88,
    source: "Vercel Blog",
    summary: "AI SDK 的生态示例继续扩展，重点是把模型、工具调用和前端交互连接起来。",
    tags: ["AI SDK", "Next.js", "Developer Tool"],
    title: "Vercel AI SDK 示例生态适合继续关注",
    url: "https://vercel.com/blog",
    what_happened: "AI SDK 的生态示例继续扩展，重点是把模型、工具调用和前端交互连接起来。",
    why_it_matters: "如果你要做 AI Web App，它能减少 provider 切换、流式输出和工具调用的重复代码。"
  },
  {
    action: "把 release notes 的结构复制到自己的项目：新增、修复、迁移、风险分别写清楚。",
    category: "ai_news",
    content_type: "engineering",
    created_at: now,
    published_at: now,
    reason: "好的 changelog 能让开发者快速判断升级成本，比营销稿更有价值。",
    score: 86,
    source: "Hugging Face Blog",
    summary: "模型、数据集和推理工具的更新继续围绕更低部署成本与更清晰开发体验展开。",
    tags: ["Open Source", "Model Ops", "Developer Experience"],
    title: "开源 AI 工具更新更强调部署成本和开发体验",
    url: "https://huggingface.co/blog",
    what_happened: "模型、数据集和推理工具的更新继续围绕更低部署成本与更清晰开发体验展开。",
    why_it_matters: "对个人开发者来说，部署成本和文档质量常常决定一个工具能不能真正落地。"
  },
  {
    action: "记录一个你想做的 AI 功能，然后写下它需要哪些后端队列、重试和日志能力。",
    category: "ai_news",
    content_type: "engineering",
    created_at: now,
    published_at: now,
    reason: "Agent 产品不是只有 prompt，稳定的后端任务系统会成为差异点。",
    score: 84,
    source: "InfoQ 中文",
    summary: "社区讨论把 LLM 工作流接入后端任务队列、缓存、审计日志和失败重试的工程实践。",
    tags: ["Java", "Backend", "Agent"],
    title: "Agent 落地开始回到后端工程基本功",
    url: "https://www.infoq.cn/",
    what_happened: "社区讨论把 LLM 工作流接入后端任务队列、缓存、审计日志和失败重试的工程实践。",
    why_it_matters: "这很适合 Java/Backend 开发者切入 AI 产品，不必只和前端 prompt 工具竞争。"
  },
  {
    action: "选一个热门仓库看 README 首屏、安装命令和示例复杂度，判断它为什么增长快。",
    category: "tool",
    content_type: "tool",
    created_at: now,
    published_at: now,
    reason: "GitHub Trending 能帮助发现开发者已经在试用的真实工具。",
    score: 83,
    source: "GitHub Trending",
    summary: "AI 编码、RAG 评测、浏览器自动化和本地模型工具仍是开源增长热点。",
    tags: ["GitHub", "Open Source", "AI Coding"],
    title: "GitHub Trending 继续出现 AI Coding 与自动化工具",
    url: "https://github.com/trending",
    what_happened: "AI 编码、RAG 评测、浏览器自动化和本地模型工具仍是开源增长热点。",
    why_it_matters: "这些仓库比新闻更接近真实需求，可以作为个人项目选题和技术栈参考。"
  },
  {
    action: "找一篇原始工程博客，对照它的架构图写一个 5 行版本的实现思路。",
    category: "ai_news",
    content_type: "engineering",
    created_at: now,
    published_at: now,
    reason: "工程博客通常比二手资讯更能暴露设计取舍和真实限制。",
    score: 81,
    source: "Engineering Blogs",
    summary: "多家公司继续公开 AI 功能上线后的延迟、成本、缓存和评估体系经验。",
    tags: ["Engineering", "LLM Eval", "Backend"],
    title: "AI 功能落地经验开始集中在成本、缓存和评估",
    url: "https://github.com/kilimchoi/engineering-blogs",
    what_happened: "多家公司继续公开 AI 功能上线后的延迟、成本、缓存和评估体系经验。",
    why_it_matters: "这些经验能帮你避免只做 Demo，提前理解上线后会遇到的性能和质量问题。"
  },
  {
    action: "做一个最小 benchmark：同一个问题分别走关键词、embedding 和 LLM 判断，比较成本与效果。",
    category: "tool",
    content_type: "engineering",
    created_at: now,
    published_at: now,
    reason: "很多 AI 信息处理任务可以先用便宜规则解决，再把 LLM 留给高价值步骤。",
    score: 79,
    source: "Hacker News",
    summary: "开发者继续讨论如何在搜索、过滤、摘要和评估之间平衡规则、向量和 LLM 调用成本。",
    tags: ["LLM Cost", "Search", "Backend"],
    title: "低成本 AI Pipeline 的关键是少让 LLM 做机械活",
    url: "https://news.ycombinator.com/",
    what_happened: "开发者继续讨论如何在搜索、过滤、摘要和评估之间平衡规则、向量和 LLM 调用成本。",
    why_it_matters: "这直接关系到你的日报能否免费或低成本长期运行。"
  },
  {
    action: "参考它的首屏：一句承诺、一个输入入口、一个立即可见的结果示例。",
    category: "product",
    content_type: "product",
    created_at: now,
    inspiration: "可以做一个更窄版本：专门帮个人开发者把会议、灵感和 issue 自动变成可执行项目日志。",
    product_name: "Granola",
    product_one_liner: "把会议记录变成结构化、可复用的 AI 笔记，而不是一份普通转录稿。",
    product_takeaways: [
      "定位很窄：先占住 AI meeting notes 的高频工作流。",
      "交互重点不是炫技，而是让用户少整理会后信息。",
      "输出形态直接贴近用户已有的笔记和协作习惯。"
    ],
    published_at: now,
    reason: "它展示了 AI 产品如何从“自动生成内容”升级为“减少整理成本”。",
    score: 87,
    source: "Product Hunt",
    summary: "Granola 这类产品把 AI 能力包装成会议后整理和知识复用工作流。",
    tags: ["Product Pattern", "AI Notes", "Workflow"],
    target_user: "高频开会的创始人、产品经理、研究员和小团队",
    title: "Product Pattern：Granola 的 AI 会议笔记工作流",
    url: "https://www.granola.ai/",
    what_happened: "Granola 这类产品把 AI 能力包装成会议后整理和知识复用工作流。",
    why_it_matters: "它的价值不在模型本身，而在把信息捕捉、整理和复用压缩成一个稳定习惯。"
  },
  {
    action: "拆它的 onboarding：用户输入一句需求后，系统如何尽快给出可编辑结果。",
    category: "product",
    content_type: "product",
    created_at: now,
    inspiration: "个人开发者可以避开通用建站，选择一个垂直场景，例如简历项目生成器、内部工具生成器或课程练习生成器。",
    product_name: "Lovable",
    product_one_liner: "把自然语言需求转成可运行 Web App，降低从想法到原型的启动成本。",
    product_takeaways: [
      "首屏直接卖结果：把你的 idea 变成 app。",
      "核心交互是持续对话加即时预览，反馈周期很短。",
      "适合学习如何把代码生成包装成非程序员也能理解的产品体验。"
    ],
    published_at: now,
    reason: "它代表了 AI App Builder 的典型产品形态，值得拆定位和交互节奏。",
    score: 85,
    source: "Product Website",
    summary: "Lovable 把 prompt、代码生成、预览和迭代放到一个连续体验里。",
    tags: ["Product Pattern", "AI Builder", "Prototype"],
    target_user: "想快速做原型的创业者、设计师和独立开发者",
    title: "Product Pattern：Lovable 如何降低做 App 的启动成本",
    url: "https://lovable.dev/",
    what_happened: "Lovable 把 prompt、代码生成、预览和迭代放到一个连续体验里。",
    why_it_matters: "它说明 AI Coding 产品的竞争点不只是生成代码，而是让用户持续看见进展。"
  },
  {
    action: "从活动页提取 3 个关键词，反推一个你能在 48 小时内交付的作品。",
    category: "hackathon",
    content_type: "opportunity",
    created_at: now,
    published_at: now,
    reason: "适合用来练习把 AI 能力包装成完整产品，而不是只交一个脚本。",
    score: 78,
    source: "Lablab.ai",
    summary: "AI 应用开发比赛持续覆盖 Agent、RAG、多模态和自动化工作流方向。",
    tags: ["Competition", "RAG", "AI App"],
    title: "AI 应用 Hackathon 适合做作品集项目",
    url: "https://lablab.ai/",
    what_happened: "AI 应用开发比赛持续覆盖 Agent、RAG、多模态和自动化工作流方向。",
    why_it_matters: "比赛给了明确 deadline 和展示场景，比无限期做 side project 更容易完成。"
  },
  {
    action: "看近期活动议程，记录一个你没接触过但能做成 Demo 的开发者主题。",
    category: "hackathon",
    content_type: "opportunity",
    created_at: now,
    published_at: now,
    reason: "开发者活动常常能提前看到公司和社区真正想推动的技术方向。",
    score: 74,
    source: "Google Developers",
    summary: "开发者活动继续围绕 AI、Web、Cloud 和移动端工具链展开。",
    tags: ["Developer Event", "Cloud", "AI"],
    title: "近期开发者活动适合补技术趋势雷达",
    url: "https://developers.google.com/events",
    what_happened: "开发者活动继续围绕 AI、Web、Cloud 和移动端工具链展开。",
    why_it_matters: "活动议程能帮你快速判断哪些主题值得投入学习和做项目。"
  }
];
