create table if not exists daily_items (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  reason text,
  url text,
  source text,
  category text,
  score int,
  published_at timestamptz,
  created_at timestamptz default now()
);

create index if not exists daily_items_created_at_idx on daily_items (created_at desc);
create index if not exists daily_items_category_score_idx on daily_items (category, score desc);
create index if not exists daily_items_url_idx on daily_items (url);

create table if not exists curiosity_items (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null,
  hook text not null,
  explanation text not null,
  key_fact text not null,
  related_topics text[] default '{}',
  difficulty int default 2,
  source text not null,
  source_url text not null,
  created_at timestamptz default now()
);

create index if not exists curiosity_items_created_at_idx on curiosity_items (created_at desc);
create index if not exists curiosity_items_category_idx on curiosity_items (category);
